# --- Taps ---
tap "armmbed/formulae"
tap "cartr/qt4"
tap "cloudflare/cloudflare"
tap "gcenx/wine"
tap "hashicorp/tap"
tap "mac-cleanup/mac-cleanup-py"
tap "messense/macos-cross-toolchains"
tap "osx-cross/avr"
tap "rioriost/parasync"
tap "sergiobenitez/osxct"
tap "tnishinaga/sigrok"
tap "tomoyanonymous/flatcam"


# Independent
brew "aider"
brew "gemini-cli"
brew "huggingface-cli"
brew "ollama", restart_service: :changed
cask "claude-code"
cask "mochi-diffusion"
brew "opencode"
brew "sqlite"

# --- Embedded & Hardware Engineering ---
brew "arduino-cli"
brew "avrdude"
brew "icarus-verilog"
brew "lpc21isp"
brew "open-ocd"
brew "platformio"
brew "armmbed/formulae/arm-none-eabi-gcc"
brew "osx-cross/avr/avr-gcc@9"
brew "sigrok-firmware-fx2lafw"
brew "tomoyanonymous/flatcam/flatcam-evo"
cask "arduino-ide"
cask "cncjs"
cask "freecad"
cask "kicad"
cask "openscad"

# --- Web & Software Development ---
brew "awscli"
brew "ccls"
brew "cfn-lint"
brew "cmake"
brew "cocoapods"
brew "cookiecutter"
brew "cppcheck"
brew "gh"
brew "kotlin"
brew "lua-language-server"
brew "mysql-client"
brew "nodenv"
brew "ocaml"
brew "python-lsp-server"
cask "postico"
cask "stoplight-studio"
cask "temurin@8"
cask "visual-studio-code"
cargo "cargo-audit"
cargo "cargo-compete"
cargo "mdbook"
cargo "ravedude"

# --- System, Terminal & Security ---
brew "coreutils"
brew "direnv"
brew "fzy"
brew "iproute2mac"
brew "lazygit"
brew "lf"
brew "neovim"
brew "nikto"
brew "nmap"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "starship"
brew "taskwarrior-tui"
brew "telnet"
brew "tmux"
brew "tree"
brew "wget"
cask "alacritty"
cask "blackhole-2ch"
cask "onyx"
cask "utm"
cask "vnc-viewer"

# --- Graphics, Media & Design ---
brew "agg"
brew "ffmpeg"
brew "imagemagick"
cask "font-eb-garamond"
cask "font-hack-nerd-font"
cask "krita"
cask "obs"
cask "vlc"

# --- Productivity & Documentation ---
brew "asciinema"
brew "cloc"
brew "multitime"
brew "pandoc"
brew "typst"
cask "alfred"
cask "drawio"
cask "mactex-no-gui"
cask "obsidian"
cask "prince"
cask "processing"

# --- Communication & Utilities ---
brew "aria2"
brew "cloudflared"
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
brew "xorriso"
cask "appcleaner"
cask "cyberduck"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "keybase"
cask "keyboard-cleaner"
cask "keycastr"
cask "microsoft-teams"
cask "raspberry-pi-imager"
cask "slack"
cask "zap"
