[Distribution]
Distribution=ubuntu
Release=noble

[Content]
PostInstallationScripts=mkosi.postinst
BasePackages=yes
Packages=
    linux-generic
    systemd-boot
    cloud-init
    sudo
    zsh
    curl
    ca-certificates
    tar
    gnupg
    rsync
    lsb-release
    dbus
    locales
    systemd-resolved
    openssh-server
    iproute2
    fdisk
    parted
    dosfstools
    grub-efi
    grub-common
    gum

[Output]
Format=disk
Bootable=yes
Output=yuseiito-dev-live_pine.raw
