[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main,universe,restricted,multiverse

[Content]
PostInstallationScripts=mkosi.postinst.chroot
Packages=
    base-files
    apt
    linux-generic
    systemd-boot
    cloud-init
    sudo
    zsh
    curl
    ca-certificates
    tar
    gnupg
    rsync
    lsb-release
    dbus
    locales
    systemd-resolved
    openssh-server
    iproute2
    fdisk
    parted
    dosfstools
    grub-efi
    grub-common
Bootable=yes
Hostname=pine
CleanPackageMetadata=yes

[Build]
WithNetwork=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
Format=disk
