FROM ubuntu:24.04

LABEL org.opencontainers.image.source=https://github.com/yuseiito/dotfiles
LABEL org.opencontainers.image.description="Yusei's dotfiles Container. Variant `pine`"
LABEL org.opencontainers.image.licenses=MIT

# Supress interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Minimal setup before running setup.sh
RUN apt-get update && \
    apt-get install -y sudo curl ca-certificates tar

# Allow passwordless sudo for the ubuntu user
RUN echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu

USER ubuntu
ENV HOME=/home/ubuntu
ENV USER=ubuntu
ENV LOGNAME=ubuntu
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV SHELL=/usr/bin/zsh

COPY --chown=ubuntu:ubuntu ./ /home/ubuntu/dotfiles/
WORKDIR /home/ubuntu/dotfiles/


ENV DOTFILES_ROLE=pine
RUN bash setup.sh

WORKDIR /home/ubuntu

HEALTHCHECK --interval=60s --timeout=30s --start-period=5s --retries=3 \
    CMD goss --gossfile /home/ubuntu/dotfiles/mitamae/roles/pine/goss.yaml validate

CMD ["/usr/bin/zsh"]
