FROM ubuntu:24.04

# Supress interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Minimal setup before running setup.sh
RUN apt-get update && \
    apt-get install -y sudo curl ca-certificates tar

COPY ./ /root/dotfiles/
WORKDIR /root/dotfiles/

ENV DOTFILES_ROLE=pine
RUN bash setup.sh

CMD ["/bin/bash"]
