FROM debian:bookworm-slim@sha256:74d56e3931e0d5a1dd51f8c8a2466d21de84a271cd3b5a733b803aa91abf4421

LABEL org.opencontainers.image.source=https://github.com/yuseiito/dotfiles
LABEL org.opencontainers.image.description="Yusei's dotfiles Container. Variant `plum`"
LABEL org.opencontainers.image.licenses=MIT

# Suppress interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Minimal setup before running setup.sh
RUN apt-get update && \
    apt-get install -y sudo curl ca-certificates tar

# Allow passwordless sudo for the debian user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID debian && \
    useradd --uid $USER_UID --gid $USER_GID -m -s /bin/bash debian && \
    echo "debian ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/debian && \
    chmod 0440 /etc/sudoers.d/debian


USER debian
ENV HOME=/home/debian
ENV USER=debian
ENV LOGNAME=debian
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV SHELL=/usr/bin/zsh

COPY --chown=debian:debian ./ /home/debian/dotfiles/
WORKDIR /home/debian/dotfiles/

RUN sudo apt-get update

ENV DOTFILES_ROLE=plum
RUN bash ./setup.sh && \
    sudo install -m 755 docker/entrypoint.sh /usr/local/bin/entrypoint.sh

WORKDIR /home/debian

HEALTHCHECK --interval=60s --timeout=30s --start-period=5s --retries=3 \
    CMD ["/usr/local/bin/entrypoint.sh", "goss", "--gossfile", "/home/debian/dotfiles/mitamae/roles/plum/goss.yaml", "validate"]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/bin/zsh"]
