gossfile:
  ../../cookbooks/goss/goss.yaml: {}
  ../../cookbooks/git/goss.yaml: {}
  ../../cookbooks/rust/goss.yaml: {}
  ../../cookbooks/uv/goss.yaml: {}
  ../../cookbooks/nodenv/goss.yaml: {}
  ../../cookbooks/zsh/goss.yaml: {}
  ../../cookbooks/neovim/goss.yaml: {}
  ../../cookbooks/base_tools/goss.yaml: {}
  ../../cookbooks/tmux/goss.yaml: {}
  ../../cookbooks/binutils/goss.yaml: {}
  ../../cookbooks/starship/goss.yaml: {}
  ../../cookbooks/direnv/goss.yaml: {}
  ../../cookbooks/lazygit/goss.yaml: {}
  ../../cookbooks/cloudflared/goss.yaml: {}
  ../../cookbooks/aria2/goss.yaml: {}
  ../../cookbooks/nmap/goss.yaml: {}
  ../../cookbooks/nikto/goss.yaml: {}
  ../../cookbooks/awscli/goss.yaml: {}
  ../../cookbooks/cfn-lint/goss.yaml: {}
  ../../cookbooks/gh/goss.yaml: {}
  ../../cookbooks/ollama/goss.yaml: {}
  ../../cookbooks/huggingface-cli/goss.yaml: {}
  ../../cookbooks/aider/goss.yaml: {}
  ../../cookbooks/claude-code/goss.yaml: {}
  ../../cookbooks/gemini-cli/goss.yaml: {}
  ../../cookbooks/opencode/goss.yaml: {}
  ../../cookbooks/sdkman/goss.yaml: {}
  ../../cookbooks/kotlin/goss.yaml: {}
  ../../cookbooks/ocaml/goss.yaml: {}
  ../../cookbooks/lua-language-server/goss.yaml: {}
  ../../cookbooks/cmake/goss.yaml: {}
  ../../cookbooks/ccls/goss.yaml: {}
  ../../cookbooks/cloc/goss.yaml: {}
  ../../cookbooks/ffmpeg/goss.yaml: {}
  ../../cookbooks/imagemagick/goss.yaml: {}
  ../../cookbooks/pandoc/goss.yaml: {}
  ../../cookbooks/sqlite/goss.yaml: {}
  ../../cookbooks/mysql-client/goss.yaml: {}
  ../../cookbooks/asciinema/goss.yaml: {}
  ../../cookbooks/arduino-cli/goss.yaml: {}
  ../../cookbooks/avrdude/goss.yaml: {}
  ../../cookbooks/icarus-verilog/goss.yaml: {}
  ../../cookbooks/openocd/goss.yaml: {}
  ../../cookbooks/platformio/goss.yaml: {}
  ../../cookbooks/llvm/goss.yaml: {}
  ../../cookbooks/terraform-ls/goss.yaml: {}
  ../../cookbooks/pylsp/goss.yaml: {}
  ../../cookbooks/typescript-language-server/goss.yaml: {}
  ../../cookbooks/biome/goss.yaml: {}
  ../../cookbooks/prisma-language-server/goss.yaml: {}
