gossfile:
  ../../cookbooks/goss/goss.yaml: {}
  ../../cookbooks/git/goss.yaml: {}
  ../../cookbooks/rust/goss.yaml: {}
  ../../cookbooks/uv/goss.yaml: {}
  ../../cookbooks/nodenv/goss.yaml: {}
  ../../cookbooks/zsh/goss.yaml: {}
  ../../cookbooks/neovim/goss.yaml: {}
  ../../cookbooks/base_tools/goss.yaml: {}
  ../../cookbooks/binutils/goss.yaml: {}
  ../../cookbooks/starship/goss.yaml: {}
  ../../cookbooks/direnv/goss.yaml: {}
  ../../cookbooks/lazygit/goss.yaml: {}
  ../../cookbooks/cloudflared/goss.yaml: {}
  ../../cookbooks/awscli/goss.yaml: {}
  ../../cookbooks/cfn-lint/goss.yaml: {}
  ../../cookbooks/gh/goss.yaml: {}
  ../../cookbooks/docker/goss.yaml: {}
  ../../cookbooks/ollama/goss.yaml: {}
  ../../cookbooks/huggingface-cli/goss.yaml: {}
  ../../cookbooks/aider/goss.yaml: {}
  ../../cookbooks/claude-code/goss.yaml: {}
  ../../cookbooks/gemini-cli/goss.yaml: {}
  ../../cookbooks/opencode/goss.yaml: {}
  ../../cookbooks/llvm/goss.yaml: {}
  ../../cookbooks/terraform-ls/goss.yaml: {}
  ../../cookbooks/pylsp/goss.yaml: {}
  ../../cookbooks/typescript-language-server/goss.yaml: {}
  ../../cookbooks/biome/goss.yaml: {}
  ../../cookbooks/prisma-language-server/goss.yaml: {}
  ../../cookbooks/lua-language-server/goss.yaml: {}
  ../../cookbooks/cloc/goss.yaml: {}
