gossfile:
  ../../cookbooks/goss/goss.yaml: {}
  ../../cookbooks/git/goss.yaml: {}
  ../../cookbooks/rust/goss.yaml: {}
  ../../cookbooks/uv/goss.yaml: {}
  ../../cookbooks/nodenv/goss.yaml: {}
  ../../cookbooks/ruby/goss.yaml: {}
  ../../cookbooks/dotfiles-utils/goss.yaml: {}
  ../../cookbooks/zsh/goss.yaml: {}
  ../../cookbooks/neovim/goss.yaml: {}
  ../../cookbooks/base_tools/goss.yaml: {}
  ../../cookbooks/binutils/goss.yaml: {}
  ../../cookbooks/starship/goss.yaml: {}
  ../../cookbooks/direnv/goss.yaml: {}
  ../../cookbooks/zoxide/goss.yaml: {}
  ../../cookbooks/lazygit/goss.yaml: {}
  ../../cookbooks/fastfetch/goss.yaml: {}
  ../../cookbooks/cloudflared/goss.yaml: {}
  ../../cookbooks/awscli/goss.yaml: {}
  ../../cookbooks/prowler/goss.yaml: {}
  ../../cookbooks/google-cloud-sdk/goss.yaml: {}
  ../../cookbooks/cfn-lint/goss.yaml: {}
  ../../cookbooks/gh/goss.yaml: {}
  ../../cookbooks/docker/goss.yaml: {}
  ../../cookbooks/devcontainer-cli/goss.yaml: {}
  ../../cookbooks/ollama/goss.yaml: {}
  ../../cookbooks/huggingface-cli/goss.yaml: {}
  ../../cookbooks/aider/goss.yaml: {}
  ../../cookbooks/claude-code/goss.yaml: {}
  ../../cookbooks/git-commit-claude/goss.yaml: {}
  ../../cookbooks/gemini-cli/goss.yaml: {}
  ../../cookbooks/opencode/goss.yaml: {}
  ../../cookbooks/corretto21/goss.yaml: {}
  ../../cookbooks/llvm/goss.yaml: {}
  ../../cookbooks/terraform-ls/goss.yaml: {}
  ../../cookbooks/pylsp/goss.yaml: {}
  ../../cookbooks/typescript-language-server/goss.yaml: {}
  ../../cookbooks/biome/goss.yaml: {}
  ../../cookbooks/prisma-language-server/goss.yaml: {}
  ../../cookbooks/lua-language-server/goss.yaml: {}
  ../../cookbooks/kotlin-lsp/goss.yaml: {}
  ../../cookbooks/cloc/goss.yaml: {}
  ../../cookbooks/imagemagick/goss.yaml: {}
  ../../cookbooks/graphviz/goss.yaml: {}
  ../../cookbooks/ghostscript/goss.yaml: {}
