AllCops:
  NewCops: enable


# Exclude them from the BlockLength check to avoid unnecessary warnings,
# since cookbooks, roles, and custom resources often contain long blocks.
  Exclude:
    - "cookbooks/**/*.rb"
    - "roles/**/*.rb"

Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Disable the EnvHome cop since it doesn't work with mruby.
Style/EnvHome:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
